// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForInsertRunLogs implements pgx.CopyFromSource.
type iteratorForInsertRunLogs struct {
	rows                 []InsertRunLogsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertRunLogs) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertRunLogs) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].RunID,
		r.rows[0].Seq,
		r.rows[0].Stream,
		r.rows[0].Ts,
		r.rows[0].ByteOffset,
		r.rows[0].ByteLength,
	}, nil
}

func (r iteratorForInsertRunLogs) Err() error {
	return nil
}

// The index rows for captured output (task 2.2). :copyfrom so a batch is one
// COPY rather than one round trip per line - a chatty script can produce
// thousands of lines, and the supervisor's capture loop is on the critical
// path of every run.
//
// The bodies are NOT here: byte_offset/byte_length address the run's log file
// (ARCHITECTURE.md §4.1, internal/runlog). Never insert a row for a line the
// writer has not flushed - the row is what tells a reader those bytes exist.
func (q *Queries) InsertRunLogs(ctx context.Context, arg []InsertRunLogsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"run_logs"}, []string{"run_id", "seq", "stream", "ts", "byte_offset", "byte_length"}, &iteratorForInsertRunLogs{rows: arg})
}
