// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJob = `-- name: GetJob :one
SELECT id, repo_id, runtime_id, manifest_path, name, enabled, created_at,
       description, script_path, command, image_ref, timeout_seconds,
       synced_commit_sha, synced_at, deleted_at
FROM jobs
WHERE id = $1
`

// Does not filter soft-deleted jobs. A run keeps pointing at its job after the
// manifest is gone, and "what did this run execute" must still answer.
func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.RuntimeID,
		&i.ManifestPath,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
		&i.Description,
		&i.ScriptPath,
		&i.Command,
		&i.ImageRef,
		&i.TimeoutSeconds,
		&i.SyncedCommitSha,
		&i.SyncedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getJobByName = `-- name: GetJobByName :one
SELECT id, repo_id, runtime_id, manifest_path, name, enabled, created_at,
       description, script_path, command, image_ref, timeout_seconds,
       synced_commit_sha, synced_at, deleted_at
FROM jobs
WHERE name = $1 AND deleted_at IS NULL
`

// Live jobs only: `descendence jobs run <name>` must not resolve to a job
// whose manifest has been deleted. Names are unique among live jobs
// (jobs_name_live_idx), so this returns at most one row.
func (q *Queries) GetJobByName(ctx context.Context, name string) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByName, name)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.RuntimeID,
		&i.ManifestPath,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
		&i.Description,
		&i.ScriptPath,
		&i.Command,
		&i.ImageRef,
		&i.TimeoutSeconds,
		&i.SyncedCommitSha,
		&i.SyncedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, repo_id, runtime_id, manifest_path, name, enabled, created_at,
       description, script_path, command, image_ref, timeout_seconds,
       synced_commit_sha, synced_at, deleted_at
FROM jobs
WHERE deleted_at IS NULL
  AND ($1::text IS NULL
       OR (name, id) > ($1::text, $2::bigint))
ORDER BY name ASC, id ASC
LIMIT $3
`

type ListJobsParams struct {
	CursorName pgtype.Text `json:"cursor_name"`
	CursorID   pgtype.Int8 `json:"cursor_id"`
	RowLimit   int32       `json:"row_limit"`
}

// Keyset pagination on (name, id) ASC, matching jobs_name_id_idx. Ordered by
// name because a job list is a catalogue, not a timeline - the opposite of
// ListRuns, whose newest row is the interesting one.
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.CursorName, arg.CursorID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.RuntimeID,
			&i.ManifestPath,
			&i.Name,
			&i.Enabled,
			&i.CreatedAt,
			&i.Description,
			&i.ScriptPath,
			&i.Command,
			&i.ImageRef,
			&i.TimeoutSeconds,
			&i.SyncedCommitSha,
			&i.SyncedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByRepo = `-- name: ListJobsByRepo :many
SELECT id, repo_id, runtime_id, manifest_path, name, enabled, created_at,
       description, script_path, command, image_ref, timeout_seconds,
       synced_commit_sha, synced_at, deleted_at
FROM jobs
WHERE repo_id = $1
ORDER BY manifest_path ASC
`

// Every job of a repository, soft-deleted ones included. Used by the scan to
// work out what is new, what changed and what vanished before it writes
// anything - which is also why it must not filter on deleted_at, since a
// resurrected manifest has to be recognised as the row it already owns.
func (q *Queries) ListJobsByRepo(ctx context.Context, repoID int64) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByRepo, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.RepoID,
			&i.RuntimeID,
			&i.ManifestPath,
			&i.Name,
			&i.Enabled,
			&i.CreatedAt,
			&i.Description,
			&i.ScriptPath,
			&i.Command,
			&i.ImageRef,
			&i.TimeoutSeconds,
			&i.SyncedCommitSha,
			&i.SyncedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setJobEnabled = `-- name: SetJobEnabled :execrows
UPDATE jobs
SET enabled = $2
WHERE id = $1 AND deleted_at IS NULL
`

type SetJobEnabledParams struct {
	ID      int64 `json:"id"`
	Enabled bool  `json:"enabled"`
}

// The only mutation the API performs on a job, and the only column git does
// not own. :execrows so the handler can tell "no such live job" (0 rows) from
// a successful write, rather than reporting success for a job that is not
// there.
func (q *Queries) SetJobEnabled(ctx context.Context, arg SetJobEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setJobEnabled, arg.ID, arg.Enabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteJobsNotIn = `-- name: SoftDeleteJobsNotIn :many
UPDATE jobs
SET deleted_at = now()
WHERE repo_id = $1
  AND deleted_at IS NULL
  AND manifest_path <> ALL($2::text[])
RETURNING id, name, manifest_path
`

type SoftDeleteJobsNotInParams struct {
	RepoID    int64    `json:"repo_id"`
	KeepPaths []string `json:"keep_paths"`
}

type SoftDeleteJobsNotInRow struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	ManifestPath string `json:"manifest_path"`
}

// The other half of a scan: manifests that were there last time and are not
// there now.
//
// Soft, because runs.job_id is ON DELETE SET NULL - a hard delete would
// quietly sever every past run from the job it ran, which is the one thing
// §2.4 (a past run must be explainable) does not allow. An empty keep_paths
// array correctly deletes every job in the repository: a repository whose
// manifests have all been removed has no jobs.
func (q *Queries) SoftDeleteJobsNotIn(ctx context.Context, arg SoftDeleteJobsNotInParams) ([]SoftDeleteJobsNotInRow, error) {
	rows, err := q.db.Query(ctx, softDeleteJobsNotIn, arg.RepoID, arg.KeepPaths)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SoftDeleteJobsNotInRow
	for rows.Next() {
		var i SoftDeleteJobsNotInRow
		if err := rows.Scan(&i.ID, &i.Name, &i.ManifestPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertJob = `-- name: UpsertJob :one
INSERT INTO jobs (repo_id, manifest_path, name, description, script_path,
                  command, image_ref, timeout_seconds, synced_commit_sha, runtime_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (repo_id, manifest_path) DO UPDATE
SET name              = EXCLUDED.name,
    description       = EXCLUDED.description,
    script_path       = EXCLUDED.script_path,
    command           = EXCLUDED.command,
    image_ref         = EXCLUDED.image_ref,
    timeout_seconds   = EXCLUDED.timeout_seconds,
    synced_commit_sha = EXCLUDED.synced_commit_sha,
    runtime_id        = EXCLUDED.runtime_id,
    synced_at         = now(),
    deleted_at        = NULL
RETURNING id, repo_id, runtime_id, manifest_path, name, enabled, created_at,
          description, script_path, command, image_ref, timeout_seconds,
          synced_commit_sha, synced_at, deleted_at
`

type UpsertJobParams struct {
	RepoID          int64       `json:"repo_id"`
	ManifestPath    string      `json:"manifest_path"`
	Name            string      `json:"name"`
	Description     pgtype.Text `json:"description"`
	ScriptPath      string      `json:"script_path"`
	Command         []string    `json:"command"`
	ImageRef        pgtype.Text `json:"image_ref"`
	TimeoutSeconds  pgtype.Int4 `json:"timeout_seconds"`
	SyncedCommitSha string      `json:"synced_commit_sha"`
	RuntimeID       pgtype.Int8 `json:"runtime_id"`
}

// The write half of a scan (task 3.4).
//
// Every column set here is copied from a manifest and owned by git. `enabled`
// is conspicuously absent from the UPDATE and that is the point: it is the one
// fact about a job that this installation owns rather than the repository, so
// a sync must never reset an operator's decision to pause a job. If `enabled`
// ever appears in this statement, pausing a misbehaving job becomes something
// the next sync silently undoes.
//
// deleted_at is cleared, which is how a manifest that comes back resurrects
// the *same* job row - and with it every past run that points at that id.
//
// runtime_id is resolved by the caller (jobsync, task 4.6) from the
// manifest's `runtime:` name before this is called - a name is what git can
// express, but the FK is what the image_or_runtime CHECK and a run's
// creation actually need.
func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, upsertJob,
		arg.RepoID,
		arg.ManifestPath,
		arg.Name,
		arg.Description,
		arg.ScriptPath,
		arg.Command,
		arg.ImageRef,
		arg.TimeoutSeconds,
		arg.SyncedCommitSha,
		arg.RuntimeID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.RuntimeID,
		&i.ManifestPath,
		&i.Name,
		&i.Enabled,
		&i.CreatedAt,
		&i.Description,
		&i.ScriptPath,
		&i.Command,
		&i.ImageRef,
		&i.TimeoutSeconds,
		&i.SyncedCommitSha,
		&i.SyncedAt,
		&i.DeletedAt,
	)
	return i, err
}
