// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: principals.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTokenPrincipal = `-- name: CreateTokenPrincipal :one
INSERT INTO principals (kind, name, token_hash, token_hint, expires_at)
VALUES ('token', $1, $2, $3, $4)
RETURNING id, kind, name, token_hash, token_hint, password_hash, created_at, expires_at, revoked_at, last_login_at
`

type CreateTokenPrincipalParams struct {
	Name      string             `json:"name"`
	TokenHash []byte             `json:"token_hash"`
	TokenHint pgtype.Text        `json:"token_hint"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateTokenPrincipalRow struct {
	ID           int64              `json:"id"`
	Kind         string             `json:"kind"`
	Name         string             `json:"name"`
	TokenHash    []byte             `json:"token_hash"`
	TokenHint    pgtype.Text        `json:"token_hint"`
	PasswordHash []byte             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) CreateTokenPrincipal(ctx context.Context, arg CreateTokenPrincipalParams) (CreateTokenPrincipalRow, error) {
	row := q.db.QueryRow(ctx, createTokenPrincipal,
		arg.Name,
		arg.TokenHash,
		arg.TokenHint,
		arg.ExpiresAt,
	)
	var i CreateTokenPrincipalRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const createUserPrincipal = `-- name: CreateUserPrincipal :one
INSERT INTO principals (kind, name, password_hash)
VALUES ('user', $1, $2)
RETURNING id, kind, name, token_hash, token_hint, password_hash, created_at, expires_at, revoked_at, last_login_at
`

type CreateUserPrincipalParams struct {
	Name         string `json:"name"`
	PasswordHash []byte `json:"password_hash"`
}

type CreateUserPrincipalRow struct {
	ID           int64              `json:"id"`
	Kind         string             `json:"kind"`
	Name         string             `json:"name"`
	TokenHash    []byte             `json:"token_hash"`
	TokenHint    pgtype.Text        `json:"token_hint"`
	PasswordHash []byte             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) CreateUserPrincipal(ctx context.Context, arg CreateUserPrincipalParams) (CreateUserPrincipalRow, error) {
	row := q.db.QueryRow(ctx, createUserPrincipal, arg.Name, arg.PasswordHash)
	var i CreateUserPrincipalRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getPrincipalByID = `-- name: GetPrincipalByID :one
SELECT id, kind, name, token_hash, token_hint, password_hash, created_at, expires_at, revoked_at, last_login_at
FROM principals
WHERE id = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

type GetPrincipalByIDRow struct {
	ID           int64              `json:"id"`
	Kind         string             `json:"kind"`
	Name         string             `json:"name"`
	TokenHash    []byte             `json:"token_hash"`
	TokenHint    pgtype.Text        `json:"token_hint"`
	PasswordHash []byte             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) GetPrincipalByID(ctx context.Context, id int64) (GetPrincipalByIDRow, error) {
	row := q.db.QueryRow(ctx, getPrincipalByID, id)
	var i GetPrincipalByIDRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getPrincipalByTokenHash = `-- name: GetPrincipalByTokenHash :one
SELECT id, kind, name, token_hash, token_hint, password_hash, created_at, expires_at, revoked_at, last_login_at
FROM principals
WHERE token_hash = $1
  AND kind = 'token'
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

type GetPrincipalByTokenHashRow struct {
	ID           int64              `json:"id"`
	Kind         string             `json:"kind"`
	Name         string             `json:"name"`
	TokenHash    []byte             `json:"token_hash"`
	TokenHint    pgtype.Text        `json:"token_hint"`
	PasswordHash []byte             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) GetPrincipalByTokenHash(ctx context.Context, tokenHash []byte) (GetPrincipalByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getPrincipalByTokenHash, tokenHash)
	var i GetPrincipalByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserPrincipalByName = `-- name: GetUserPrincipalByName :one
SELECT id, kind, name, token_hash, token_hint, password_hash, created_at, expires_at, revoked_at, last_login_at
FROM principals
WHERE name = $1
  AND kind = 'user'
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

type GetUserPrincipalByNameRow struct {
	ID           int64              `json:"id"`
	Kind         string             `json:"kind"`
	Name         string             `json:"name"`
	TokenHash    []byte             `json:"token_hash"`
	TokenHint    pgtype.Text        `json:"token_hint"`
	PasswordHash []byte             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

// Returns last_login_at as it stood *before* this call - LoginHandler reads
// it here, then overwrites it via TouchPrincipalLastLogin, so the value
// returned to the client is genuinely "when you logged in last time", not
// "now".
func (q *Queries) GetUserPrincipalByName(ctx context.Context, name string) (GetUserPrincipalByNameRow, error) {
	row := q.db.QueryRow(ctx, getUserPrincipalByName, name)
	var i GetUserPrincipalByNameRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listPrincipalsByKind = `-- name: ListPrincipalsByKind :many
SELECT id, kind, name, token_hash, token_hint, password_hash, created_at, expires_at, revoked_at, last_login_at
FROM principals
WHERE kind = $1
ORDER BY name
`

type ListPrincipalsByKindRow struct {
	ID           int64              `json:"id"`
	Kind         string             `json:"kind"`
	Name         string             `json:"name"`
	TokenHash    []byte             `json:"token_hash"`
	TokenHint    pgtype.Text        `json:"token_hint"`
	PasswordHash []byte             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}

// Task 8.2/8.3: the users/tokens list endpoints. Unpaginated - a homelab has
// a handful of principals, not thousands, matching ListSchedulesByJob's
// reasoning for skipping cursor pagination.
func (q *Queries) ListPrincipalsByKind(ctx context.Context, kind string) ([]ListPrincipalsByKindRow, error) {
	rows, err := q.db.Query(ctx, listPrincipalsByKind, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrincipalsByKindRow
	for rows.Next() {
		var i ListPrincipalsByKindRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.TokenHash,
			&i.TokenHint,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokePrincipal = `-- name: RevokePrincipal :execrows
UPDATE principals
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

// Soft-revoke, never a hard delete: runs.principal_id is ON DELETE RESTRICT,
// and revoked_at IS NULL is already the filter every lookup query above
// applies, so a revoked principal simply stops authenticating - its run
// history stays queryable and explainable.
func (q *Queries) RevokePrincipal(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, revokePrincipal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchPrincipalLastLogin = `-- name: TouchPrincipalLastLogin :execrows
UPDATE principals
SET last_login_at = now()
WHERE id = $1
`

// Called by LoginHandler right after password verification succeeds - see
// GetUserPrincipalByName's comment for why the two queries are sequenced
// this way rather than combined into one.
func (q *Queries) TouchPrincipalLastLogin(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, touchPrincipalLastLogin, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePrincipalPasswordHash = `-- name: UpdatePrincipalPasswordHash :execrows
UPDATE principals
SET password_hash = $2
WHERE id = $1
`

type UpdatePrincipalPasswordHashParams struct {
	ID           int64  `json:"id"`
	PasswordHash []byte `json:"password_hash"`
}

func (q *Queries) UpdatePrincipalPasswordHash(ctx context.Context, arg UpdatePrincipalPasswordHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, updatePrincipalPasswordHash, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
