// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: principals.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTokenPrincipal = `-- name: CreateTokenPrincipal :one
INSERT INTO principals (kind, name, token_hash, token_hint, scopes)
VALUES ('token', $1, $2, $3, $4)
RETURNING id, kind, name, token_hash, token_hint, scopes, created_at, expires_at, revoked_at
`

type CreateTokenPrincipalParams struct {
	Name      string      `json:"name"`
	TokenHash []byte      `json:"token_hash"`
	TokenHint pgtype.Text `json:"token_hint"`
	Scopes    []string    `json:"scopes"`
}

func (q *Queries) CreateTokenPrincipal(ctx context.Context, arg CreateTokenPrincipalParams) (Principal, error) {
	row := q.db.QueryRow(ctx, createTokenPrincipal,
		arg.Name,
		arg.TokenHash,
		arg.TokenHint,
		arg.Scopes,
	)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getPrincipalByTokenHash = `-- name: GetPrincipalByTokenHash :one
SELECT id, kind, name, token_hash, token_hint, scopes, created_at, expires_at, revoked_at
FROM principals
WHERE token_hash = $1
  AND kind = 'token'
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
`

func (q *Queries) GetPrincipalByTokenHash(ctx context.Context, tokenHash []byte) (Principal, error) {
	row := q.db.QueryRow(ctx, getPrincipalByTokenHash, tokenHash)
	var i Principal
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
