// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repos.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRepo = `-- name: CreateRepo :one
INSERT INTO repos (name, path, kind, remote_url, default_branch)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, path, kind, remote_url, created_at, default_branch,
          last_synced_at, last_synced_commit_sha
`

type CreateRepoParams struct {
	Name          string      `json:"name"`
	Path          string      `json:"path"`
	Kind          string      `json:"kind"`
	RemoteUrl     pgtype.Text `json:"remote_url"`
	DefaultBranch string      `json:"default_branch"`
}

// Task 3.2/3.6. The bare repository on disk is created first and the row
// second: a row pointing at a directory that does not exist is a repository
// nothing can read, whereas a directory with no row is merely orphaned and
// visible to an operator. `path` is recorded rather than derived because the
// database stays the source of truth for where a repository lives, even
// though the layout under GIT_REPO_DIR is predictable (§2 principle 2).
func (q *Queries) CreateRepo(ctx context.Context, arg CreateRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, createRepo,
		arg.Name,
		arg.Path,
		arg.Kind,
		arg.RemoteUrl,
		arg.DefaultBranch,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Kind,
		&i.RemoteUrl,
		&i.CreatedAt,
		&i.DefaultBranch,
		&i.LastSyncedAt,
		&i.LastSyncedCommitSha,
	)
	return i, err
}

const getRepo = `-- name: GetRepo :one
SELECT id, name, path, kind, remote_url, created_at, default_branch,
       last_synced_at, last_synced_commit_sha
FROM repos
WHERE id = $1
`

func (q *Queries) GetRepo(ctx context.Context, id int64) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepo, id)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Kind,
		&i.RemoteUrl,
		&i.CreatedAt,
		&i.DefaultBranch,
		&i.LastSyncedAt,
		&i.LastSyncedCommitSha,
	)
	return i, err
}

const getRepoByName = `-- name: GetRepoByName :one
SELECT id, name, path, kind, remote_url, created_at, default_branch,
       last_synced_at, last_synced_commit_sha
FROM repos
WHERE name = $1
`

// The CLI addresses repositories by name; ids never appear in a command line.
func (q *Queries) GetRepoByName(ctx context.Context, name string) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByName, name)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Kind,
		&i.RemoteUrl,
		&i.CreatedAt,
		&i.DefaultBranch,
		&i.LastSyncedAt,
		&i.LastSyncedCommitSha,
	)
	return i, err
}

const listRepos = `-- name: ListRepos :many
SELECT id, name, path, kind, remote_url, created_at, default_branch,
       last_synced_at, last_synced_commit_sha
FROM repos
WHERE $1::text IS NULL
   OR (name, id) > ($1::text, $2::bigint)
ORDER BY name ASC, id ASC
LIMIT $3
`

type ListReposParams struct {
	CursorName pgtype.Text `json:"cursor_name"`
	CursorID   pgtype.Int8 `json:"cursor_id"`
	RowLimit   int32       `json:"row_limit"`
}

// Keyset pagination on (name, id) ASC. A repository list is a catalogue rather
// than a timeline, so it is ordered by name - the opposite of ListRuns, and
// the reason the cursor here is a name rather than a timestamp.
func (q *Queries) ListRepos(ctx context.Context, arg ListReposParams) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listRepos, arg.CursorName, arg.CursorID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.Kind,
			&i.RemoteUrl,
			&i.CreatedAt,
			&i.DefaultBranch,
			&i.LastSyncedAt,
			&i.LastSyncedCommitSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRepoSynced = `-- name: MarkRepoSynced :exec
UPDATE repos
SET last_synced_at = now(),
    last_synced_commit_sha = $2
WHERE id = $1
`

type MarkRepoSyncedParams struct {
	ID                  int64       `json:"id"`
	LastSyncedCommitSha pgtype.Text `json:"last_synced_commit_sha"`
}

// Records what the last successful scan saw (task 3.4). Deliberately *not* an
// input to the next scan: a scan always re-reads HEAD and rebuilds the whole
// projection, because trusting a stored "last seen" would make a sync that
// half-failed invisible to the one after it.
func (q *Queries) MarkRepoSynced(ctx context.Context, arg MarkRepoSyncedParams) error {
	_, err := q.db.Exec(ctx, markRepoSynced, arg.ID, arg.LastSyncedCommitSha)
	return err
}
