// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPrincipalByIDWithRole = `-- name: GetPrincipalByIDWithRole :one
SELECT p.id, p.kind, p.name, p.token_hint, p.created_at, p.expires_at, p.revoked_at, r.name AS role_name
FROM principals p
LEFT JOIN principal_roles pr ON pr.principal_id = p.id
LEFT JOIN roles r ON r.id = pr.role_id
WHERE p.id = $1
`

type GetPrincipalByIDWithRoleRow struct {
	ID        int64              `json:"id"`
	Kind      string             `json:"kind"`
	Name      string             `json:"name"`
	TokenHint pgtype.Text        `json:"token_hint"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	RoleName  pgtype.Text        `json:"role_name"`
}

func (q *Queries) GetPrincipalByIDWithRole(ctx context.Context, id int64) (GetPrincipalByIDWithRoleRow, error) {
	row := q.db.QueryRow(ctx, getPrincipalByIDWithRole, id)
	var i GetPrincipalByIDWithRoleRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.TokenHint,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RoleName,
	)
	return i, err
}

const getPrincipalPermissions = `-- name: GetPrincipalPermissions :many
SELECT p.key
FROM principal_roles pr
JOIN role_permissions rp ON rp.role_id = pr.role_id
JOIN permissions p ON p.id = rp.permission_id
WHERE pr.principal_id = $1
`

// One indexed join per request (principal_roles' PK covers principal_id),
// same cost class as the token/session lookups in principals.sql/sessions.sql
// - not a new tier of expense. Called once per request by RequireAuth and
// collected into a set; RequirePermission then does an in-memory lookup.
func (q *Queries) GetPrincipalPermissions(ctx context.Context, principalID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getPrincipalPermissions, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrincipalRoleName = `-- name: GetPrincipalRoleName :one
SELECT r.name
FROM principal_roles pr
JOIN roles r ON r.id = pr.role_id
WHERE pr.principal_id = $1
`

// Powers whoami's role field and the "which role does this principal have"
// lookups in the users/tokens API - a principal has exactly one role
// (principal_roles.principal_id is UNIQUE).
func (q *Queries) GetPrincipalRoleName(ctx context.Context, principalID int64) (string, error) {
	row := q.db.QueryRow(ctx, getPrincipalRoleName, principalID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, created_at FROM roles WHERE name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listPrincipalsByKindWithRole = `-- name: ListPrincipalsByKindWithRole :many
SELECT p.id, p.kind, p.name, p.token_hint, p.created_at, p.expires_at, p.revoked_at, r.name AS role_name
FROM principals p
LEFT JOIN principal_roles pr ON pr.principal_id = p.id
LEFT JOIN roles r ON r.id = pr.role_id
WHERE p.kind = $1
ORDER BY p.name
`

type ListPrincipalsByKindWithRoleRow struct {
	ID        int64              `json:"id"`
	Kind      string             `json:"kind"`
	Name      string             `json:"name"`
	TokenHint pgtype.Text        `json:"token_hint"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	RoleName  pgtype.Text        `json:"role_name"`
}

// The users/tokens list endpoints (task 8.2/8.3), joined so the list view
// doesn't do an N+1 role lookup per row.
func (q *Queries) ListPrincipalsByKindWithRole(ctx context.Context, kind string) ([]ListPrincipalsByKindWithRoleRow, error) {
	rows, err := q.db.Query(ctx, listPrincipalsByKindWithRole, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPrincipalsByKindWithRoleRow
	for rows.Next() {
		var i ListPrincipalsByKindWithRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.TokenHint,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissionKeys = `-- name: ListRolePermissionKeys :many
SELECT p.key
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.key
`

// Task 8.4's GET /api/v1/roles response includes each role's permission
// list, read-only (decision #30: fixed built-in roles, no editor).
func (q *Queries) ListRolePermissionKeys(ctx context.Context, roleID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolePermissionKeys, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, created_at FROM roles ORDER BY id
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPrincipalRole = `-- name: SetPrincipalRole :exec
INSERT INTO principal_roles (principal_id, role_id)
VALUES ($1, $2)
ON CONFLICT (principal_id) DO UPDATE SET role_id = EXCLUDED.role_id
`

type SetPrincipalRoleParams struct {
	PrincipalID int64 `json:"principal_id"`
	RoleID      int64 `json:"role_id"`
}

// Used both by cmd/seed (bootstrap, bypassing the API/RequirePermission by
// construction the same way it already bypasses "you need users:write" by
// not calling the API at all) and by the users/tokens API's create and
// role-reassignment handlers. principal_id is UNIQUE, so this is an upsert:
// assigning a new role to an already-role'd principal replaces it rather
// than erroring, since "exactly one role" is the invariant, not "insert
// once".
func (q *Queries) SetPrincipalRole(ctx context.Context, arg SetPrincipalRoleParams) error {
	_, err := q.db.Exec(ctx, setPrincipalRole, arg.PrincipalID, arg.RoleID)
	return err
}
