// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runlogs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRunLogs = `-- name: CountRunLogs :one
SELECT count(*) FROM run_logs WHERE run_id = $1
`

// Whether a run has any index rows at all. Distinguishes "printed nothing"
// from "output was pruned" when read alongside runs.logs_pruned_at.
func (q *Queries) CountRunLogs(ctx context.Context, runID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countRunLogs, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRunLogs = `-- name: DeleteRunLogs :exec
DELETE FROM run_logs WHERE run_id = $1
`

// Clears a run's index, to match runlog.Create truncating its file. Used when
// the reconciler adopts a run and recaptures its output from scratch (task
// 1.15 meeting 2.1): the old rows address offsets in a file that no longer
// exists, so leaving them behind would point readers at the wrong bytes.
func (q *Queries) DeleteRunLogs(ctx context.Context, runID int64) error {
	_, err := q.db.Exec(ctx, deleteRunLogs, runID)
	return err
}

type InsertRunLogsParams struct {
	RunID      int64              `json:"run_id"`
	Seq        int64              `json:"seq"`
	Stream     string             `json:"stream"`
	Ts         pgtype.Timestamptz `json:"ts"`
	ByteOffset int64              `json:"byte_offset"`
	ByteLength int32              `json:"byte_length"`
}

const listRunLogs = `-- name: ListRunLogs :many
SELECT run_id, seq, stream, ts, byte_offset, byte_length
FROM run_logs
WHERE run_id = $1
  AND seq > $2
ORDER BY seq
LIMIT $3
`

type ListRunLogsParams struct {
	RunID    int64 `json:"run_id"`
	AfterSeq int64 `json:"after_seq"`
	RowLimit int32 `json:"row_limit"`
}

// One page of a run's log index, in sequence order, starting strictly after
// after_seq. after_seq = 0 means "from the beginning", which is also what an
// SSE client reconnecting without a Last-Event-ID asks for (task 2.6).
// Matches the (run_id, seq) primary key, so no extra index is needed.
func (q *Queries) ListRunLogs(ctx context.Context, arg ListRunLogsParams) ([]RunLog, error) {
	rows, err := q.db.Query(ctx, listRunLogs, arg.RunID, arg.AfterSeq, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunLog
	for rows.Next() {
		var i RunLog
		if err := rows.Scan(
			&i.RunID,
			&i.Seq,
			&i.Stream,
			&i.Ts,
			&i.ByteOffset,
			&i.ByteLength,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsWithExpiredLogs = `-- name: ListRunsWithExpiredLogs :many
SELECT id
FROM runs
WHERE logs_pruned_at IS NULL
  AND finished_at IS NOT NULL
  AND finished_at < $1
ORDER BY finished_at
LIMIT $2
`

type ListRunsWithExpiredLogsParams struct {
	Cutoff   pgtype.Timestamptz `json:"cutoff"`
	RowLimit int32              `json:"row_limit"`
}

// The retention sweep's input (task 2.2): finished runs past the retention
// window whose logs have not been pruned yet, oldest first. Matches
// runs_logs_prunable_idx. Bounded by row_limit so one sweep does a bounded
// amount of work rather than trying to clear a year's backlog in a single
// pass.
func (q *Queries) ListRunsWithExpiredLogs(ctx context.Context, arg ListRunsWithExpiredLogsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listRunsWithExpiredLogs, arg.Cutoff, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRunLogsPruned = `-- name: MarkRunLogsPruned :exec
UPDATE runs SET logs_pruned_at = now() WHERE id = $1
`

// Records that the sweep has been over this run. Set last, after the rows and
// the file are actually gone, so a crash mid-sweep leaves the run to be swept
// again rather than marking it done with its logs still on disk.
func (q *Queries) MarkRunLogsPruned(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markRunLogsPruned, id)
	return err
}
