// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelQueuedRun = `-- name: CancelQueuedRun :execrows
UPDATE runs
SET state = 'cancelled',
    cancel_requested_at = now(),
    finished_at = now()
WHERE id = $1
  AND state = 'queued'
`

// Task 2.8, the half of cancellation the API can do alone: a queued run has
// no container, so there is nothing to stop and nothing to ask the supervisor
// for. State and outcome are written in one guarded statement.
//
// The state guard is what makes this safe against the claim loop. Both this
// and ClaimNextQueuedRun update the same row under `state = 'queued'`, so
// exactly one of them wins: either the run is cancelled before it ever starts,
// or it is claimed and the caller falls back to RequestRunCancel. There is no
// window where both happen, and none where neither does.
//
// cancel_requested_at is set here too even though nothing reads it for a
// queued run - it is the record that this run was cancelled rather than
// having failed on its own.
func (q *Queries) CancelQueuedRun(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, cancelQueuedRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimNextQueuedRun = `-- name: ClaimNextQueuedRun :one
WITH claimed AS (
    SELECT id FROM runs
    WHERE state = 'queued'
    ORDER BY queued_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE runs
SET state = 'running', started_at = now()
FROM claimed
WHERE runs.id = claimed.id
RETURNING runs.id, runs.principal_id, runs.state, runs.idempotency_key,
          runs.image_ref, runs.argv, runs.timeout_seconds, runs.container_id,
          runs.exit_code, runs.failure_reason, runs.cancel_requested_at,
          runs.queued_at, runs.started_at, runs.finished_at, runs.job_id,
          runs.commit_sha, runs.runtime_id, runs.image_digest,
          runs.params_json, runs.logs_pruned_at
`

// The supervisor's claim loop (task 1.12). The CTE's FOR UPDATE SKIP LOCKED
// picks the oldest queued run not already locked by another supervisor (or
// another iteration of this same loop, if ever run concurrently), and the
// outer UPDATE atomically transitions it to running in the same statement -
// no separate SELECT-then-UPDATE race window. Zero rows back (pgx.ErrNoRows)
// just means the queue is empty right now, not an error.
func (q *Queries) ClaimNextQueuedRun(ctx context.Context) (Run, error) {
	row := q.db.QueryRow(ctx, claimNextQueuedRun)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.State,
		&i.IdempotencyKey,
		&i.ImageRef,
		&i.Argv,
		&i.TimeoutSeconds,
		&i.ContainerID,
		&i.ExitCode,
		&i.FailureReason,
		&i.CancelRequestedAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.JobID,
		&i.CommitSha,
		&i.RuntimeID,
		&i.ImageDigest,
		&i.ParamsJson,
		&i.LogsPrunedAt,
	)
	return i, err
}

const createJobRun = `-- name: CreateJobRun :one
INSERT INTO runs (principal_id, image_ref, argv, timeout_seconds, idempotency_key,
                  job_id, commit_sha)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (principal_id, idempotency_key) DO NOTHING
RETURNING id, principal_id, state, idempotency_key, image_ref, argv,
          timeout_seconds, container_id, exit_code, failure_reason,
          cancel_requested_at, queued_at, started_at, finished_at, job_id,
          commit_sha, runtime_id, image_digest, params_json, logs_pruned_at
`

type CreateJobRunParams struct {
	PrincipalID    int64       `json:"principal_id"`
	ImageRef       string      `json:"image_ref"`
	Argv           []string    `json:"argv"`
	TimeoutSeconds int32       `json:"timeout_seconds"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	JobID          pgtype.Int8 `json:"job_id"`
	CommitSha      pgtype.Text `json:"commit_sha"`
}

// Task 3.5. The same insert as CreateRun, plus the two columns that make a run
// explainable: which job it is, and the exact commit its definition and script
// were read from.
//
// image_ref and argv are still written onto the run rather than looked up from
// the job at execution time, deliberately. A run records what it will do, not
// a pointer to somewhere that might say something different later - which is
// the same reason commit_sha is pinned here rather than resolved by the
// supervisor.
func (q *Queries) CreateJobRun(ctx context.Context, arg CreateJobRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createJobRun,
		arg.PrincipalID,
		arg.ImageRef,
		arg.Argv,
		arg.TimeoutSeconds,
		arg.IdempotencyKey,
		arg.JobID,
		arg.CommitSha,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.State,
		&i.IdempotencyKey,
		&i.ImageRef,
		&i.Argv,
		&i.TimeoutSeconds,
		&i.ContainerID,
		&i.ExitCode,
		&i.FailureReason,
		&i.CancelRequestedAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.JobID,
		&i.CommitSha,
		&i.RuntimeID,
		&i.ImageDigest,
		&i.ParamsJson,
		&i.LogsPrunedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (principal_id, image_ref, argv, timeout_seconds, idempotency_key)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (principal_id, idempotency_key) DO NOTHING
RETURNING id, principal_id, state, idempotency_key, image_ref, argv,
          timeout_seconds, container_id, exit_code, failure_reason,
          cancel_requested_at, queued_at, started_at, finished_at, job_id,
          commit_sha, runtime_id, image_digest, params_json, logs_pruned_at
`

type CreateRunParams struct {
	PrincipalID    int64       `json:"principal_id"`
	ImageRef       string      `json:"image_ref"`
	Argv           []string    `json:"argv"`
	TimeoutSeconds int32       `json:"timeout_seconds"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

// Idempotency_key is NULL when the caller sent no Idempotency-Key header;
// Postgres never treats NULL as conflicting with anything, so unkeyed runs
// always insert. A repeated key for the same principal hits the unique index
// and DO NOTHING skips the insert - :one then returns pgx.ErrNoRows, which is
// the caller's signal to look the original up via GetRunByIdempotencyKey.
func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.db.QueryRow(ctx, createRun,
		arg.PrincipalID,
		arg.ImageRef,
		arg.Argv,
		arg.TimeoutSeconds,
		arg.IdempotencyKey,
	)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.State,
		&i.IdempotencyKey,
		&i.ImageRef,
		&i.Argv,
		&i.TimeoutSeconds,
		&i.ContainerID,
		&i.ExitCode,
		&i.FailureReason,
		&i.CancelRequestedAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.JobID,
		&i.CommitSha,
		&i.RuntimeID,
		&i.ImageDigest,
		&i.ParamsJson,
		&i.LogsPrunedAt,
	)
	return i, err
}

const finishRun = `-- name: FinishRun :execrows
UPDATE runs
SET state = $2,
    exit_code = $3,
    container_id = $4,
    failure_reason = $5,
    finished_at = now()
WHERE id = $1
  AND state IN ('queued', 'running')
`

type FinishRunParams struct {
	ID            int64       `json:"id"`
	State         string      `json:"state"`
	ExitCode      pgtype.Int4 `json:"exit_code"`
	ContainerID   pgtype.Text `json:"container_id"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

// Task 1.13. state is always a terminal one here -
// runs_state_timestamps_check requires finished_at whenever state is
// terminal, which this always sets.
//
// The state guard makes a terminal state final (task 1.14): a run that has
// already succeeded must never be rewritten as lost by a reconciler that
// was slow to notice, and an outcome must never be overwritten by a stale
// process. :execrows so the caller can tell "recorded" from "someone else
// already finished this run" instead of silently clobbering a real result.
func (q *Queries) FinishRun(ctx context.Context, arg FinishRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishRun,
		arg.ID,
		arg.State,
		arg.ExitCode,
		arg.ContainerID,
		arg.FailureReason,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRun = `-- name: GetRun :one
SELECT id, principal_id, state, idempotency_key, image_ref, argv,
       timeout_seconds, container_id, exit_code, failure_reason,
       cancel_requested_at, queued_at, started_at, finished_at, job_id,
       commit_sha, runtime_id, image_digest, params_json, logs_pruned_at
FROM runs
WHERE id = $1
`

func (q *Queries) GetRun(ctx context.Context, id int64) (Run, error) {
	row := q.db.QueryRow(ctx, getRun, id)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.State,
		&i.IdempotencyKey,
		&i.ImageRef,
		&i.Argv,
		&i.TimeoutSeconds,
		&i.ContainerID,
		&i.ExitCode,
		&i.FailureReason,
		&i.CancelRequestedAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.JobID,
		&i.CommitSha,
		&i.RuntimeID,
		&i.ImageDigest,
		&i.ParamsJson,
		&i.LogsPrunedAt,
	)
	return i, err
}

const getRunByIdempotencyKey = `-- name: GetRunByIdempotencyKey :one
SELECT id, principal_id, state, idempotency_key, image_ref, argv,
       timeout_seconds, container_id, exit_code, failure_reason,
       cancel_requested_at, queued_at, started_at, finished_at, job_id,
       commit_sha, runtime_id, image_digest, params_json, logs_pruned_at
FROM runs
WHERE principal_id = $1 AND idempotency_key = $2
`

type GetRunByIdempotencyKeyParams struct {
	PrincipalID    int64       `json:"principal_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) GetRunByIdempotencyKey(ctx context.Context, arg GetRunByIdempotencyKeyParams) (Run, error) {
	row := q.db.QueryRow(ctx, getRunByIdempotencyKey, arg.PrincipalID, arg.IdempotencyKey)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.State,
		&i.IdempotencyKey,
		&i.ImageRef,
		&i.Argv,
		&i.TimeoutSeconds,
		&i.ContainerID,
		&i.ExitCode,
		&i.FailureReason,
		&i.CancelRequestedAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.JobID,
		&i.CommitSha,
		&i.RuntimeID,
		&i.ImageDigest,
		&i.ParamsJson,
		&i.LogsPrunedAt,
	)
	return i, err
}

const isRunCancelRequested = `-- name: IsRunCancelRequested :one
SELECT (cancel_requested_at IS NOT NULL)::boolean AS cancel_requested
FROM runs
WHERE id = $1
`

// The supervisor's poll while a run is in flight (task 2.8).
//
// Polled rather than pushed. The api-to-supervisor direction has no
// notification channel - LISTEN/NOTIFY carries log watermarks the other way
// (decision #19) - and building one for this would inherit its lossiness,
// which is tolerable for "there is more output to read" and not tolerable for
// "stop this run". A cancel that silently does nothing is worse than a cancel
// that takes a second. Reads the primary key, so the cost is a lookup per
// second per in-flight run.
func (q *Queries) IsRunCancelRequested(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, isRunCancelRequested, id)
	var cancel_requested bool
	err := row.Scan(&cancel_requested)
	return cancel_requested, err
}

const listNonTerminalRuns = `-- name: ListNonTerminalRuns :many
SELECT id, principal_id, state, idempotency_key, image_ref, argv,
       timeout_seconds, container_id, exit_code, failure_reason,
       cancel_requested_at, queued_at, started_at, finished_at, job_id,
       commit_sha, runtime_id, image_digest, params_json, logs_pruned_at
FROM runs
WHERE state IN ('queued', 'running')
`

// The reconciler's input (task 1.15): every run that isn't in a terminal
// state, matching runs_active_idx.
func (q *Queries) ListNonTerminalRuns(ctx context.Context) ([]Run, error) {
	rows, err := q.db.Query(ctx, listNonTerminalRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.State,
			&i.IdempotencyKey,
			&i.ImageRef,
			&i.Argv,
			&i.TimeoutSeconds,
			&i.ContainerID,
			&i.ExitCode,
			&i.FailureReason,
			&i.CancelRequestedAt,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.JobID,
			&i.CommitSha,
			&i.RuntimeID,
			&i.ImageDigest,
			&i.ParamsJson,
			&i.LogsPrunedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT id, principal_id, state, idempotency_key, image_ref, argv,
       timeout_seconds, container_id, exit_code, failure_reason,
       cancel_requested_at, queued_at, started_at, finished_at, job_id,
       commit_sha, runtime_id, image_digest, params_json, logs_pruned_at
FROM runs
WHERE $1::timestamptz IS NULL
   OR (queued_at, id) < ($1::timestamptz, $2::bigint)
ORDER BY queued_at DESC, id DESC
LIMIT $3
`

type ListRunsParams struct {
	CursorQueuedAt pgtype.Timestamptz `json:"cursor_queued_at"`
	CursorID       pgtype.Int8        `json:"cursor_id"`
	RowLimit       int32              `json:"row_limit"`
}

// Keyset (seek) pagination on (queued_at DESC, id DESC), matching
// runs_queued_at_id_desc_idx. A NULL cursor means "first page"; otherwise
// the row-wise comparison below is exactly the "strictly after the cursor,
// in this DESC order" condition.
func (q *Queries) ListRuns(ctx context.Context, arg ListRunsParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRuns, arg.CursorQueuedAt, arg.CursorID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.State,
			&i.IdempotencyKey,
			&i.ImageRef,
			&i.Argv,
			&i.TimeoutSeconds,
			&i.ContainerID,
			&i.ExitCode,
			&i.FailureReason,
			&i.CancelRequestedAt,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.JobID,
			&i.CommitSha,
			&i.RuntimeID,
			&i.ImageDigest,
			&i.ParamsJson,
			&i.LogsPrunedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunsByJob = `-- name: ListRunsByJob :many
SELECT id, principal_id, state, idempotency_key, image_ref, argv,
       timeout_seconds, container_id, exit_code, failure_reason,
       cancel_requested_at, queued_at, started_at, finished_at, job_id,
       commit_sha, runtime_id, image_digest, params_json, logs_pruned_at
FROM runs
WHERE job_id = $1::bigint
  AND ($2::timestamptz IS NULL
       OR (queued_at, id) < ($2::timestamptz, $3::bigint))
ORDER BY queued_at DESC, id DESC
LIMIT $4
`

type ListRunsByJobParams struct {
	JobID          int64              `json:"job_id"`
	CursorQueuedAt pgtype.Timestamptz `json:"cursor_queued_at"`
	CursorID       pgtype.Int8        `json:"cursor_id"`
	RowLimit       int32              `json:"row_limit"`
}

// Runs of one job, newest first, matching runs_job_id_idx. Same keyset shape
// as ListRuns.
func (q *Queries) ListRunsByJob(ctx context.Context, arg ListRunsByJobParams) ([]Run, error) {
	rows, err := q.db.Query(ctx, listRunsByJob,
		arg.JobID,
		arg.CursorQueuedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Run
	for rows.Next() {
		var i Run
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.State,
			&i.IdempotencyKey,
			&i.ImageRef,
			&i.Argv,
			&i.TimeoutSeconds,
			&i.ContainerID,
			&i.ExitCode,
			&i.FailureReason,
			&i.CancelRequestedAt,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
			&i.JobID,
			&i.CommitSha,
			&i.RuntimeID,
			&i.ImageDigest,
			&i.ParamsJson,
			&i.LogsPrunedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requestRunCancel = `-- name: RequestRunCancel :execrows
UPDATE runs
SET cancel_requested_at = now()
WHERE id = $1
  AND state = 'running'
`

// Task 2.8, the other half: a running run belongs to the supervisor, which
// holds the container and is the only process allowed to stop it. This
// records the request; the supervisor performs it and writes the terminal
// state itself.
//
// Guarded on 'running' so a request can never land on a run that has already
// finished, which would leave a terminal run marked as cancellation-pending
// forever. Setting it twice is harmless - the second call moves the timestamp
// and changes nothing else - so a client retrying a cancel needs no special
// handling.
func (q *Queries) RequestRunCancel(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, requestRunCancel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRunContainerID = `-- name: SetRunContainerID :exec
UPDATE runs
SET container_id = $2
WHERE id = $1
  AND state = 'running'
`

type SetRunContainerIDParams struct {
	ID          int64       `json:"id"`
	ContainerID pgtype.Text `json:"container_id"`
}

// Records the container as soon as it is created, rather than waiting for
// FinishRun (found in Phase 1e: a running run showed containerId: null, so
// there was no way to find the container of a run that was still going -
// exactly when you most want it). Guarded on state so a run that has
// somehow already finished is never touched.
func (q *Queries) SetRunContainerID(ctx context.Context, arg SetRunContainerIDParams) error {
	_, err := q.db.Exec(ctx, setRunContainerID, arg.ID, arg.ContainerID)
	return err
}
