// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtimes.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimNextPendingRuntimeBuild = `-- name: ClaimNextPendingRuntimeBuild :one
WITH claimed AS (
    SELECT id FROM runtimes
    WHERE build_status = 'pending'
    ORDER BY created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE runtimes
SET build_status = 'building'
FROM claimed
WHERE runtimes.id = claimed.id
RETURNING runtimes.id, runtimes.name, runtimes.base_image, runtimes.sys_packages,
          runtimes.lang_manifest, runtimes.image_digest, runtimes.build_status,
          runtimes.built_at, runtimes.created_at, runtimes.lang,
          runtimes.input_hash, runtimes.build_error, runtimes.image_pruned_at
`

// The supervisor's build claim loop (task 4.4/4.5), same CTE shape as
// ClaimNextQueuedRun: FOR UPDATE SKIP LOCKED picks the oldest pending
// runtime not already locked, and the outer UPDATE atomically transitions it
// to building in the same statement - no separate SELECT-then-UPDATE race
// window. Zero rows back (pgx.ErrNoRows) just means nothing is queued.
func (q *Queries) ClaimNextPendingRuntimeBuild(ctx context.Context) (Runtime, error) {
	row := q.db.QueryRow(ctx, claimNextPendingRuntimeBuild)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseImage,
		&i.SysPackages,
		&i.LangManifest,
		&i.ImageDigest,
		&i.BuildStatus,
		&i.BuiltAt,
		&i.CreatedAt,
		&i.Lang,
		&i.InputHash,
		&i.BuildError,
		&i.ImagePrunedAt,
	)
	return i, err
}

const createRuntime = `-- name: CreateRuntime :one
INSERT INTO runtimes (name, base_image, sys_packages, lang, lang_manifest, input_hash)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, base_image, sys_packages, lang_manifest, image_digest,
          build_status, built_at, created_at, lang, input_hash, build_error,
          image_pruned_at
`

type CreateRuntimeParams struct {
	Name         string      `json:"name"`
	BaseImage    string      `json:"base_image"`
	SysPackages  []string    `json:"sys_packages"`
	Lang         string      `json:"lang"`
	LangManifest pgtype.Text `json:"lang_manifest"`
	InputHash    string      `json:"input_hash"`
}

// input_hash is computed by the caller (internal/runtimebuild) from
// (base_image, sys_packages, lang, lang_manifest) - the same hash doubles as
// the build tag, so it is owned by the renderer, not by SQL.
func (q *Queries) CreateRuntime(ctx context.Context, arg CreateRuntimeParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, createRuntime,
		arg.Name,
		arg.BaseImage,
		arg.SysPackages,
		arg.Lang,
		arg.LangManifest,
		arg.InputHash,
	)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseImage,
		&i.SysPackages,
		&i.LangManifest,
		&i.ImageDigest,
		&i.BuildStatus,
		&i.BuiltAt,
		&i.CreatedAt,
		&i.Lang,
		&i.InputHash,
		&i.BuildError,
		&i.ImagePrunedAt,
	)
	return i, err
}

const getRuntime = `-- name: GetRuntime :one
SELECT id, name, base_image, sys_packages, lang_manifest, image_digest,
       build_status, built_at, created_at, lang, input_hash, build_error,
       image_pruned_at
FROM runtimes
WHERE id = $1
`

func (q *Queries) GetRuntime(ctx context.Context, id int64) (Runtime, error) {
	row := q.db.QueryRow(ctx, getRuntime, id)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseImage,
		&i.SysPackages,
		&i.LangManifest,
		&i.ImageDigest,
		&i.BuildStatus,
		&i.BuiltAt,
		&i.CreatedAt,
		&i.Lang,
		&i.InputHash,
		&i.BuildError,
		&i.ImagePrunedAt,
	)
	return i, err
}

const getRuntimeByName = `-- name: GetRuntimeByName :one
SELECT id, name, base_image, sys_packages, lang_manifest, image_digest,
       build_status, built_at, created_at, lang, input_hash, build_error,
       image_pruned_at
FROM runtimes
WHERE name = $1
`

func (q *Queries) GetRuntimeByName(ctx context.Context, name string) (Runtime, error) {
	row := q.db.QueryRow(ctx, getRuntimeByName, name)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseImage,
		&i.SysPackages,
		&i.LangManifest,
		&i.ImageDigest,
		&i.BuildStatus,
		&i.BuiltAt,
		&i.CreatedAt,
		&i.Lang,
		&i.InputHash,
		&i.BuildError,
		&i.ImagePrunedAt,
	)
	return i, err
}

const listPrunableRuntimes = `-- name: ListPrunableRuntimes :many
SELECT id, name, base_image, sys_packages, lang_manifest, image_digest,
       build_status, built_at, created_at, lang, input_hash, build_error,
       image_pruned_at
FROM runtimes
WHERE build_status = 'ready'
  AND image_pruned_at IS NULL
  AND built_at < $1
`

// Candidates for the prune sweep (task 4.7): built, not yet pruned, and
// built before the cutoff the caller supplies. "Unused" (not referenced by
// any recent run) is checked separately in Go against ListRuntimeIDsInUseSince,
// since expressing "no run in the last N days" and "no run ever, on a
// still-live job" as one SQL predicate would bury two different questions in
// one WHERE clause.
func (q *Queries) ListPrunableRuntimes(ctx context.Context, builtAt pgtype.Timestamptz) ([]Runtime, error) {
	rows, err := q.db.Query(ctx, listPrunableRuntimes, builtAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Runtime
	for rows.Next() {
		var i Runtime
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseImage,
			&i.SysPackages,
			&i.LangManifest,
			&i.ImageDigest,
			&i.BuildStatus,
			&i.BuiltAt,
			&i.CreatedAt,
			&i.Lang,
			&i.InputHash,
			&i.BuildError,
			&i.ImagePrunedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimeIDsInUseSince = `-- name: ListRuntimeIDsInUseSince :many
SELECT runtime_id FROM runs
WHERE runtime_id IS NOT NULL AND queued_at >= $1
UNION
SELECT runtime_id FROM jobs
WHERE runtime_id IS NOT NULL AND deleted_at IS NULL
`

// Runtime ids referenced by a run started on or after the cutoff, plus every
// runtime a live (non-deleted) job still names - the two ways a runtime is
// "in use" that the prune sweep must not delete out from under.
func (q *Queries) ListRuntimeIDsInUseSince(ctx context.Context, queuedAt pgtype.Timestamptz) ([]pgtype.Int8, error) {
	rows, err := q.db.Query(ctx, listRuntimeIDsInUseSince, queuedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Int8
	for rows.Next() {
		var runtime_id pgtype.Int8
		if err := rows.Scan(&runtime_id); err != nil {
			return nil, err
		}
		items = append(items, runtime_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuntimes = `-- name: ListRuntimes :many
SELECT id, name, base_image, sys_packages, lang_manifest, image_digest,
       build_status, built_at, created_at, lang, input_hash, build_error,
       image_pruned_at
FROM runtimes
WHERE ($1::text IS NULL
       OR (name, id) > ($1::text, $2::bigint))
ORDER BY name ASC, id ASC
LIMIT $3
`

type ListRuntimesParams struct {
	CursorName pgtype.Text `json:"cursor_name"`
	CursorID   pgtype.Int8 `json:"cursor_id"`
	RowLimit   int32       `json:"row_limit"`
}

// Keyset pagination on (name, id) ASC, same shape as ListJobs - a runtime
// list is a catalogue, not a timeline.
func (q *Queries) ListRuntimes(ctx context.Context, arg ListRuntimesParams) ([]Runtime, error) {
	rows, err := q.db.Query(ctx, listRuntimes, arg.CursorName, arg.CursorID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Runtime
	for rows.Next() {
		var i Runtime
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseImage,
			&i.SysPackages,
			&i.LangManifest,
			&i.ImageDigest,
			&i.BuildStatus,
			&i.BuiltAt,
			&i.CreatedAt,
			&i.Lang,
			&i.InputHash,
			&i.BuildError,
			&i.ImagePrunedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRuntimeFailed = `-- name: MarkRuntimeFailed :execrows
UPDATE runtimes
SET build_status = 'failed',
    build_error = $2
WHERE id = $1
  AND build_status = 'building'
`

type MarkRuntimeFailedParams struct {
	ID         int64       `json:"id"`
	BuildError pgtype.Text `json:"build_error"`
}

func (q *Queries) MarkRuntimeFailed(ctx context.Context, arg MarkRuntimeFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRuntimeFailed, arg.ID, arg.BuildError)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRuntimePruned = `-- name: MarkRuntimePruned :execrows
UPDATE runtimes
SET image_pruned_at = now()
WHERE id = $1
  AND image_pruned_at IS NULL
`

// Row survives (decision #18's pattern via runs.logs_pruned_at): the image
// bytes are gone but what was built, from which inputs, when, stays
// answerable.
func (q *Queries) MarkRuntimePruned(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markRuntimePruned, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRuntimeReady = `-- name: MarkRuntimeReady :execrows
UPDATE runtimes
SET build_status = 'ready',
    image_digest = $2,
    built_at = now(),
    build_error = NULL,
    image_pruned_at = NULL
WHERE id = $1
  AND build_status = 'building'
`

type MarkRuntimeReadyParams struct {
	ID          int64       `json:"id"`
	ImageDigest pgtype.Text `json:"image_digest"`
}

func (q *Queries) MarkRuntimeReady(ctx context.Context, arg MarkRuntimeReadyParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRuntimeReady, arg.ID, arg.ImageDigest)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const requestRuntimeBuild = `-- name: RequestRuntimeBuild :execrows
UPDATE runtimes
SET build_status = 'pending', build_error = NULL
WHERE id = $1
  AND build_status NOT IN ('pending', 'building')
`

// The API side of 4.5: queues a build by moving a runtime back to pending.
// Guarded to runtimes not already pending or building, so a repeat POST
// /runtimes/{id}/build while one is in flight is rejected (409) rather than
// silently queuing a second build of the same row - there is only one build
// slot per runtime, unlike runs which queue freely.
func (q *Queries) RequestRuntimeBuild(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, requestRuntimeBuild, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
