// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: schedules.sql

package store

import (
	"context"
)

const createSchedule = `-- name: CreateSchedule :one
INSERT INTO schedules (job_id, cron_expr, timezone, catch_up_policy, overlap_policy, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, job_id, cron_expr, timezone, enabled, created_at, catch_up_policy,
          overlap_policy, updated_at
`

type CreateScheduleParams struct {
	JobID         int64  `json:"job_id"`
	CronExpr      string `json:"cron_expr"`
	Timezone      string `json:"timezone"`
	CatchUpPolicy string `json:"catch_up_policy"`
	OverlapPolicy string `json:"overlap_policy"`
	Enabled       bool   `json:"enabled"`
}

// Task 5.7. cron_expr and timezone are validated by the caller
// (scheduling.CronToOnCalendar, time.LoadLocation) before this ever runs -
// this query trusts its inputs, the same posture CreateJobRun already takes
// toward its caller's manifest resolution.
func (q *Queries) CreateSchedule(ctx context.Context, arg CreateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, createSchedule,
		arg.JobID,
		arg.CronExpr,
		arg.Timezone,
		arg.CatchUpPolicy,
		arg.OverlapPolicy,
		arg.Enabled,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CronExpr,
		&i.Timezone,
		&i.Enabled,
		&i.CreatedAt,
		&i.CatchUpPolicy,
		&i.OverlapPolicy,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSchedule = `-- name: DeleteSchedule :execrows
DELETE FROM schedules
WHERE id = $1
`

// Hard delete - a schedule is operator-owned data, not a git projection
// (unlike jobs), so there is no soft-delete/explainability concern the way
// SoftDeleteJobsNotIn has one. runs.schedule_id is ON DELETE SET NULL, so a
// past run this schedule created stays explainable regardless.
func (q *Queries) DeleteSchedule(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSchedule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSchedule = `-- name: GetSchedule :one
SELECT id, job_id, cron_expr, timezone, enabled, created_at, catch_up_policy,
       overlap_policy, updated_at
FROM schedules
WHERE id = $1
`

func (q *Queries) GetSchedule(ctx context.Context, id int64) (Schedule, error) {
	row := q.db.QueryRow(ctx, getSchedule, id)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CronExpr,
		&i.Timezone,
		&i.Enabled,
		&i.CreatedAt,
		&i.CatchUpPolicy,
		&i.OverlapPolicy,
		&i.UpdatedAt,
	)
	return i, err
}

const listSchedules = `-- name: ListSchedules :many
SELECT id, job_id, cron_expr, timezone, enabled, created_at, catch_up_policy,
       overlap_policy, updated_at
FROM schedules
ORDER BY id ASC
`

// The supervisor's schedule-sync loop (task 5.3): every schedule, so the
// loop can render the expected unit pair for each and remove units for any
// id no longer present. No pagination for the same reason ListSchedulesByJob
// has none - this is a full sweep by design, not a paged listing.
func (q *Queries) ListSchedules(ctx context.Context) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.CronExpr,
			&i.Timezone,
			&i.Enabled,
			&i.CreatedAt,
			&i.CatchUpPolicy,
			&i.OverlapPolicy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchedulesByJob = `-- name: ListSchedulesByJob :many
SELECT id, job_id, cron_expr, timezone, enabled, created_at, catch_up_policy,
       overlap_policy, updated_at
FROM schedules
WHERE job_id = $1
ORDER BY id ASC
`

// No pagination (task 5.7) - a job's schedule count is small at this scale;
// see ListSchedules for the supervisor's across-all-jobs sweep.
func (q *Queries) ListSchedulesByJob(ctx context.Context, jobID int64) ([]Schedule, error) {
	rows, err := q.db.Query(ctx, listSchedulesByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Schedule
	for rows.Next() {
		var i Schedule
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.CronExpr,
			&i.Timezone,
			&i.Enabled,
			&i.CreatedAt,
			&i.CatchUpPolicy,
			&i.OverlapPolicy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSchedule = `-- name: UpdateSchedule :one
UPDATE schedules
SET cron_expr      = $2,
    timezone       = $3,
    catch_up_policy = $4,
    overlap_policy = $5,
    enabled        = $6,
    updated_at     = now()
WHERE id = $1
RETURNING id, job_id, cron_expr, timezone, enabled, created_at, catch_up_policy,
          overlap_policy, updated_at
`

type UpdateScheduleParams struct {
	ID            int64  `json:"id"`
	CronExpr      string `json:"cron_expr"`
	Timezone      string `json:"timezone"`
	CatchUpPolicy string `json:"catch_up_policy"`
	OverlapPolicy string `json:"overlap_policy"`
	Enabled       bool   `json:"enabled"`
}

// Task 5.7's PATCH. All five mutable fields are always supplied by the
// handler (the API layer already fills in "unchanged" values from the
// current row for a partial PATCH, matching PatchJobHandler's pattern) -
// there is no COALESCE here, unlike UpsertJob, because this is a direct
// operator edit rather than a re-sync that must leave one column alone.
func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) (Schedule, error) {
	row := q.db.QueryRow(ctx, updateSchedule,
		arg.ID,
		arg.CronExpr,
		arg.Timezone,
		arg.CatchUpPolicy,
		arg.OverlapPolicy,
		arg.Enabled,
	)
	var i Schedule
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.CronExpr,
		&i.Timezone,
		&i.Enabled,
		&i.CreatedAt,
		&i.CatchUpPolicy,
		&i.OverlapPolicy,
		&i.UpdatedAt,
	)
	return i, err
}
