// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (principal_id, token_hash, expires_at, id_token)
VALUES ($1, $2, $3, $4)
RETURNING id, principal_id, token_hash, created_at, expires_at, id_token
`

type CreateSessionParams struct {
	PrincipalID int64              `json:"principal_id"`
	TokenHash   []byte             `json:"token_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	IDToken     pgtype.Text        `json:"id_token"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.PrincipalID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.IDToken,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IDToken,
	)
	return i, err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :one
DELETE FROM sessions
WHERE token_hash = $1
RETURNING id_token
`

// Returns the deleted row's id_token so LogoutHandler can pass it as
// id_token_hint to the IdP's end_session_endpoint (RP-Initiated Logout) in
// the same request that ends the local session - no separate lookup query
// needed first.
func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, deleteSessionByTokenHash, tokenHash)
	var id_token pgtype.Text
	err := row.Scan(&id_token)
	return id_token, err
}

const getPrincipalBySessionTokenHash = `-- name: GetPrincipalBySessionTokenHash :one
SELECT p.id, p.kind, p.name, p.token_hash, p.token_hint, p.oidc_issuer, p.oidc_subject, p.created_at, p.expires_at, p.revoked_at, p.last_login_at
FROM sessions s
JOIN principals p ON p.id = s.principal_id
WHERE s.token_hash = $1
  AND s.expires_at > now()
  AND p.revoked_at IS NULL
`

type GetPrincipalBySessionTokenHashRow struct {
	ID          int64              `json:"id"`
	Kind        string             `json:"kind"`
	Name        string             `json:"name"`
	TokenHash   []byte             `json:"token_hash"`
	TokenHint   pgtype.Text        `json:"token_hint"`
	OidcIssuer  pgtype.Text        `json:"oidc_issuer"`
	OidcSubject pgtype.Text        `json:"oidc_subject"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) GetPrincipalBySessionTokenHash(ctx context.Context, tokenHash []byte) (GetPrincipalBySessionTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getPrincipalBySessionTokenHash, tokenHash)
	var i GetPrincipalBySessionTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.TokenHash,
		&i.TokenHint,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.LastLoginAt,
	)
	return i, err
}
