// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supervisor.sql

package store

import (
	"context"
)

const advisoryUnlock = `-- name: AdvisoryUnlock :one
SELECT pg_advisory_unlock($1::bigint) AS was_held
`

func (q *Queries) AdvisoryUnlock(ctx context.Context, lockKey int64) (bool, error) {
	row := q.db.QueryRow(ctx, advisoryUnlock, lockKey)
	var was_held bool
	err := row.Scan(&was_held)
	return was_held, err
}

const tryAdvisoryLock = `-- name: TryAdvisoryLock :one
SELECT pg_try_advisory_lock($1::bigint) AS locked
`

// Session-level, not transaction-scoped: the caller is expected to hold this
// connection open (never return it to the pool) for as long as the lock
// should be held, and explicitly AdvisoryUnlock before releasing it.
// Postgres also releases it automatically if the connection just dies.
func (q *Queries) TryAdvisoryLock(ctx context.Context, lockKey int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryAdvisoryLock, lockKey)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}
